// todo-vue/src/components/TodoItem.vue
<template>
  <div class="todoitem">
    <span class="todoitem-title">{{title}}</span>
    <button class="todoitem-remove" v-on:click="handleRemove">x</button>
  </div>
</template>

<script>
export default {
  name: "TodoItem",
  props: {
    title: String,
    id: Number
  },
  methods: {
    handleRemove: function() {
      this.$emit("removeClicked", this.id);
    }
  }
};
</script>

<style scoped>
.todoitem {
  display: flex;
  margin: 5px auto;
}

.todoitem:hover {
  background-color: #eee;
}

.todoitem-title {
  width: 100%;
}
</style>

// todo-svelte/src/TodoItem.svelte
<script>
	import { createEventDispatcher } from 'svelte';
	export let title;
	export let id;
	
	const dispatch = createEventDispatcher();
	
	function remove() {
		dispatch('removed', { id });
	}
</script>

<div class="todoitem">
	<span class="todoitem-title">{title}</span>
	<button class="todoitem-remove" on:click={remove}>x</button>
</div>

<style>
	.todoitem {
		display: flex;
		margin: 5px auto;
	}

	.todoitem:hover {
		background-color: #eee;
	}

	.todoitem-title {
		width: 100%;
	}
</style>
