// todo-react/src/components/TodoList.js
import React, { useState, useRef } from 'react'
import TodoItem from './TodoItem'
import './TodoList.css'

function TodoList() {
    const [title, setTitle] = useState('');
    const [todoItems, setTodoItems] = useState([]);
    const newTitleInput = useRef(null);

    const removeTodoItem = (id) => {
        setTodoItems([...todoItems.filter((_, i) => i !== id)]);
    }

    const addTodoItem = () => {
        if (title?.length > 0) {
            setTodoItems([...todoItems, title]);
            setTitle('');
        }
        newTitleInput.current.focus();
    }

    return (
        <div className="list">
            <h3 className="list-header">Todo List</h3>
            <div className="list-inputs">
                <input className="list-inputs-input" ref={newTitleInput} onChange={e => setTitle(e.target.value)} value={title}></input>
                <button className="list-inputs-button" onClick={addTodoItem}>+</button>
            </div>
            <>
                {todoItems && todoItems.length > 0
                    ?
                    <div className="list-todoitems">
                        {todoItems.map((t, i) => <TodoItem key={i} id={i} title={t} removeTodoItem={removeTodoItem}></TodoItem>)}
                    </div>
                    :
                    <div className="list-todoitems-placeholder-container">
                        <div>Add items to see them here!</div>
                    </div>}
            </>
        </div>
    )
}

export default TodoList

// todo-svelte/src/TodoList.svelte
<script>
	import TodoItem from './TodoItem.svelte';
	let todos = [];
	let newTodo = '';
	let ctr = 0;
	let input;
	
	function addTodoItem() {
		if(newTodo && newTodo.length > 0) {
			todos = [...todos, {title: newTodo, id: ++ctr}]
			newTodo = '';
		}
		input.focus();
	}
	
	function onRemoved(event) {
		todos = todos.filter(t => t.id !== event.detail.id);
		input.focus();
	}
</script>

<div class="list">
	<h3 class="list-header">Todo List</h3>
	<div class="list-inputs">
		<input class="list-inputs-input" bind:value={newTodo} bind:this={input} />
		<button class="list-inputs-button" on:click={addTodoItem}>+</button>
	</div>
	{#if todos && todos.length > 0}
	<div class="list-todoitems">
		{#each todos as { title, id }, i}
			<TodoItem title={title} id={id} on:removed={onRemoved} />
		{/each}
	</div>
	{:else}
	<div class="list-todoitems-placeholder-container">
		<div>Add items to see them here!</div>
	</div>
	{/if}
</div>

<style>
	.list {
		display: flex;
		flex-direction: column;
		max-width: 300px;
		margin: 0 auto;
	}

	.list-header {
		text-align: center;
	}
	.list-inputs {
		display: flex;
	}
	.list-inputs-input {
		width: 100%;
	}

	.list-todoitems-placeholder-container {
		text-align: center;
		color: #ccc;
		border: 1px dashed cornflowerblue;
		padding: 10px;
		margin-top: 5px;
	}
</style>
