// todo-svelte/src/TodoList.svelte
<script>
	import TodoItem from './TodoItem.svelte';
	let todos = [];
	let newTodo = '';
	let ctr = 0;
	let input;
	
	function addTodoItem() {
		if(newTodo && newTodo.length > 0) {
			todos = [...todos, {title: newTodo, id: ++ctr}]
			newTodo = '';
		}
		input.focus();
	}
	
	function onRemoved(event) {
		todos = todos.filter(t => t.id !== event.detail.id);
		input.focus();
	}
</script>

<div class="list">
	<h3 class="list-header">Todo List</h3>
	<div class="list-inputs">
		<input class="list-inputs-input" bind:value={newTodo} bind:this={input} />
		<button class="list-inputs-button" on:click={addTodoItem}>+</button>
	</div>
	{#if todos && todos.length > 0}
	<div class="list-todoitems">
		{#each todos as { title, id }, i}
			<TodoItem title={title} id={id} on:removed={onRemoved} />
		{/each}
	</div>
	{:else}
	<div class="list-todoitems-placeholder-container">
		<div>Add items to see them here!</div>
	</div>
	{/if}
</div>

<style>
	.list {
		display: flex;
		flex-direction: column;
		max-width: 300px;
		margin: 0 auto;
	}

	.list-header {
		text-align: center;
	}
	.list-inputs {
		display: flex;
	}
	.list-inputs-input {
		width: 100%;
	}

	.list-todoitems-placeholder-container {
		text-align: center;
		color: #ccc;
		border: 1px dashed cornflowerblue;
		padding: 10px;
		margin-top: 5px;
	}
</style>

// todo-angular/src/app/components/todo-list/todo-list.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { TodoListService } from '../../services/todo-list.service';
import { TodoItem } from 'src/app/models/todo-item';

@Component({
    selector: 'todo-list',
    templateUrl: './todo-list.component.html',
    styleUrls: ['./todo-list.component.css']
})

export class TodoListComponent implements OnInit {
    todoItems: TodoItem[];
    newTodo: string = '';
    initialCount: number = 0;
    @ViewChild('newTodoInput') newTodoInput: ElementRef;

    constructor(
        private todoListService: TodoListService
    ) { }

    ngOnInit() {
        this.todoItems = this.todoListService.todoItems;
        this.initialCount = this.todoItems.length;
    }

    addTodoItem() {
        if (this.newTodo?.length > 0) {
            this.todoItems.push({ title: this.newTodo, id: ++this.initialCount })
            this.newTodo = '';
            this.newTodoInput.nativeElement.focus();
        }
    }

    onRemoved(id: number) {
        this.todoItems = this.todoItems.filter(t => t.id !== id);
    }
}
<div class="list">
    <h3 class="list-header">Todo List</h3>
    <div class="list-inputs">
        <input class="list-inputs-input" type="text" [(ngModel)]="newTodo" #newTodoInput />
        <button class="list-inputs-button" (click)="addTodoItem()">+</button>
    </div>
    <div class="list-todoitems">
        <div *ngIf="todoItems && todoItems.length > 0; else noItems">
            <div *ngFor="let todoItem of todoItems">
                <todo-item [item]="todoItem" (removed)="onRemoved($event)"></todo-item>
            </div>
        </div>
        <ng-template #noItems>
            <div class="list-todoitems-placeholder-container">
                <div>Add items to see them here!</div>
            </div>
        </ng-template>
    </div>
</div>
